name: ride
version: '1.0'
main: com.ogga029.ride.Ride
api-version: '1.21'
authors: [ ogga029 ]
website: github.com/ogga029


commands:
  rideplayer:
    aliases:
      - rp
    permission: ride.rideplayerCMD
    description: Allows you to ride a player.
